repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3.11
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        name: bandit (excluding tests)
        exclude: ^tests/
      - id: bandit
        name: bandit (tests only)
        args: [-s, B101]
        files: ^tests/
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-json
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=20']
    - id: detect-private-key
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: name-tests-test
      args: ['--pytest-test-first']
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
